// (c) 2023, Cary Clark cclark2@gmail.com
#ifndef PathOpsTypes_DEFINED
#define PathOpsTypes_DEFINED

#include "OpMath.h"

namespace PathOpsV0Lib {

/* think about:
the data could be int or double (or long double etc.) instead of float
allow this?
*/

// an instance of the pathops engine
struct Context;

// errors that can be generated by the engine; non-fatal errors can be handled by the caller
enum class ContextError {
    none,  // no error found
	end,  // segment end does not connect to another segment (non-fatal)
	finite,  // curve points are not finite
	gap,  // assembling output required filling larger gap than expected (non-fatal)
	intersection, // curve intersection error (should not occur)
	missing,  // results do not form closed loops (non-fatal)
	toVertical, // rotating / skewing curve (to intersect) exceeds floating point range
	tree	// decision tree to join found edges is too complex
};

// collection of curves that share the same fill rules
struct Contour;

// caller defined curve type (e.g., line, arc, cubic, ...); value zero is reserved
enum class CurveType : int;

// caller-defined optional data for each curve
struct CurveUserData;

/* Curve describes a set of continuous points from start to end.
   Curve's points must be contained by a rectangle bounded by start and end.
   Curve's points must monotonically vary from start to end in x and y.
 */
struct CurveData {
	OpPoint start;
	OpPoint end;
//	CurveUserData optional;	// user data follows endpoints
};

// offset of user data (if any); immediately follows required curve points
inline size_t CurveUserDataOffset() {
	return sizeof(CurveData);
}

// location of user data
inline std::byte* CurveUserData(CurveData* curve) {
	return (std::byte*) curve + CurveUserDataOffset();
}

// the curve data, its size and type
struct Curve {
	CurveData* data;
	size_t size;  // total size pointed to by data (in bytes), including additional data, if any
	CurveType type;
};

// convenience for adding curves (e.g., Beziers) to contour
struct AddCurve {
	OpPoint* points;
	size_t size;	// size of data pointed to by points (in bytes)
	CurveType type;
};

// caller defined data representing how curves in a contour cover area
typedef void* WindingData;

// the winding data and its size
struct Winding {
	WindingData data;
	size_t size;
};

// returns if an edge starts a fill, ends a fill, or does neither and should be discarded
enum class WindKeep {
    Discard,	// must be equal to zero
    End,		// edge ends a filled area
    Start,		// edge begins a filled area
};

// output path provided by caller
typedef void* PathOutput;

// curve callbacks

// intersects the curve and axis at the axis intercept
typedef OpRoots (*AxisT)(Curve , Axis , float axisIntercept, MatchEnds);

// returns number of points in curve user data that contribute to its hull
typedef int (*HullPtCount)();

// returns true if all curve values that can describe hull points are finite 
typedef bool (*CurveIsFinite)(Curve );

// returns true if curve is line
typedef bool (*CurveIsLine)(Curve ); 

// returns OpPoint at parameter t, where: t=0 is start, t=1 is end
typedef OpPoint (*PtAtT)(Curve , float t);

// returns true if additional data is equal (e.g., lines are always equal) 
typedef bool (*CurvesEqual)(Curve , Curve );

// returns point constructs curve's hull; the curve is tightly contained by the hull's polygon
typedef OpPoint (*CurveHull)(Curve, int index);

// adds curve to output
typedef void (*CurveOutput)(Curve, bool firstPt, bool lastPt, PathOutput );

// map the control points (if any) to lie inside the bounds of the curve (e.g., start and end)
typedef void (*CurvePinCtrl)(Curve);

// reverses order of control points, if there is more than one
typedef void (*CurveReverse)(Curve);

// rotates curve user data about origin (not normalized)
typedef void (*Rotate)(Curve , OpPoint origin, OpVector scale, Curve result);

// computes part of Curve from parameter t1 to t2, both from zero to one
typedef void (*SubDivide)(Curve , float t1, float t2, Curve result);

// returns tangent vector at parameter t, where: t=0 is start, t=1 is end
typedef OpVector (*CurveTangent)(Curve, float t);

// adds curve user data to bounds
typedef void (*SetBounds)(Curve , OpRect& );

// returns either x or y pair at parameter t, where: t=0 is start, t=1 is end
typedef OpPair (*XYAtT)(Curve , OpPair t, XyChoice );

// overrides engine maximum for a curve type
typedef float (*CurveConst)(Curve );

// the collection of caller-defined functions that describe the geometry of the curve
// most caller-defined functions are optional and default to built-in behavior
struct CurveCallbacks {
	CurveOutput curveOutputFuncPtr; // !!! to do: should this default to no output? is that useful?
	AxisT axisTFuncPtr = nullptr;
	CurveHull curveHullFuncPtr = nullptr;
	CurveIsFinite curveIsFiniteFuncPtr = nullptr;
	CurveIsLine curveIsLineFuncPtr = nullptr;
	SetBounds setBoundsFuncPtr = nullptr;
	CurvePinCtrl curvePinCtrlFuncPtr = nullptr;
	CurveTangent curveTangentFuncPtr = nullptr;
	CurvesEqual curvesEqualFuncPtr = nullptr;
	PtAtT  ptAtTFuncPtr = nullptr;
	HullPtCount ptCountFuncPtr = nullptr;
	Rotate rotateFuncPtr = nullptr;
	SubDivide subDivideFuncPtr = nullptr;
	XYAtT xyAtTFuncPtr = nullptr;
	CurveReverse curveReverseFuncPtr = nullptr;
	CurveConst cutFuncPtr = nullptr;
	CurveConst normalLimitFuncPtr = nullptr;
	CurveConst interceptFuncPtr = nullptr;
};

// winding callbacks

// adds winding
typedef void (*WindingAdd)(Winding winding, Winding toAdd);

// subtracts winding
typedef void (*WindingSubtract)(Winding winding, Winding toSubtract);

// returns true if winding affects operation
typedef bool (*WindingVisible)(Winding winding);

// marks winding as having no effect
typedef void (*WindingZero)(Winding toZero);

// returns if curve transitions to a filled area and is kept; or if curve is discarded
typedef WindKeep (*WindingKeep)(Winding winding, Winding sum);

// the collection of call-defined functions that describe the winding
// !!! to do: can / should winding callbacks have defaults? maybe the unary winding rule?
struct WindingCallbacks {
	WindingAdd windingAddFuncPtr;
	WindingKeep windingKeepFuncPtr;
	WindingVisible windingVisibleFuncPtr;
	WindingZero windingZeroFuncPtr;
	WindingSubtract windingSubtractFuncPtr = nullptr;
};

// context callbacks

// initializes caller's path as empty
typedef void (*EmptyCallerPath)(PathOutput );

// returns the linear type defined by the caller
typedef CurveType (*SetLineType)(Curve );

// overrides a scalar used by the engine to test if curve intersects bounds 
typedef float (*MaxCurveValue)(Curve );

// overrides a scalar used by the engine to intersect a pair of curves 
typedef float (*MaxCurveCurveValue)(Curve , Curve );

// overrides a count used by the engine to intersect a pair of curves 
typedef int (*MaxCurveCurveCount)(Curve , Curve );

// overrides a count used by the engine to limit the memory used to assemble the result
typedef int (*MaxLimbs)(Context* );

// overrides a scalar used by the engine to describe the error allowed when assembling the result
typedef float (*MaxGap)(Context* );

// caller-defined functions, most of which customize when the engine returns an error
// most caller-defined functions are optional and have built-in defaults
struct ContextCallbacks {
	SetLineType setLineTypeFuncPtr;  // !!! to do: should this default to (CurveType) 1 ?
	EmptyCallerPath emptyCallerPathFuncPtr = nullptr;
	MaxCurveCurveValue maxSignSwapFuncPtr = nullptr;
	MaxCurveCurveValue maxOverlapFuncPtr = nullptr;
	MaxCurveCurveValue maxSplitBiasFuncPtr = nullptr;
	MaxCurveValue maxBoundedEdgeFuncPtr = nullptr;
	MaxCurveValue maxBoundedTFuncPtr = nullptr;
	MaxCurveCurveCount maxCheckSplitFuncPtr = nullptr;
	MaxCurveCurveCount maxDeepFuncPtr = nullptr;
	MaxCurveCurveCount maxShallowFuncPtr = nullptr;
	MaxCurveCurveCount maxSplitsFuncPtr = nullptr;
	MaxLimbs maxLimbsFuncPtr = nullptr;
	MaxGap maxGapFuncPtr = nullptr;
};

// return true if the engine should abort
typedef bool (*ErrorDispatch)(ContextError , Context* , Curve* );

// callder-defined function that determines if an error is fatal
struct ErrorHandler {
	ErrorDispatch errorDispatchFuncPtr;
};

} // namespace PathOpsV0Lib

#endif
