// (c) 2023, Cary Clark cclark2@gmail.com
#ifndef PathOpsTypes_DEFINED
#define PathOpsTypes_DEFINED

#include "OpMath.h"

namespace PathOpsV0Lib {

/* think about:
the data could be int or double (or long double etc.) instead of float
allow this?
*/

// an instance of the pathops engine
struct Context;

enum class UserDataType {
    none,   // unused
    outData,  // additional data used when managing which curves comprise the output
    outPath,  // pointer to caller data accumulating output path
    optional  // user-defined types start here
};

// optional user data associated with this instance of the engine
struct ContextUserData {
    void* data;
    size_t size;
    UserDataType type;
};

// errors that can be generated by the engine; non-fatal errors can be handled by the caller
enum class ContextError {
    none,  // no error found
	end,  // segment end does not connect to another segment (non-fatal)
	finite,  // curve points are not finite
	gap,  // assembling output required filling larger gap than expected (non-fatal)
	intersection, // curve intersection error (should not occur)
	loop,  // stuck resolving error in curve-curve intersection (should not occur)
	missing,  // results do not form closed loops (non-fatal)
	root,  // curve root finder returned NaN
	toVertical, // rotating / skewing curve (to intersect) exceeds floating point range
	tree	// decision tree to join found edges is too complex
};

// collection of curves that share the same fill rules
struct Contour;

// caller defined curve type (e.g., line, arc, cubic, ...)
typedef int CurveType;

static constexpr CurveType degenerateLine = (CurveType) 0;  // used when curve degenerates to line

// caller defined optional data for each curve
struct CurveUserData;

/* Curve describes a set of continuous points from start to end.
   Curve's points must be contained by a rectangle bounded by start and end.
   Curve's points must monotonically vary from start to end in x and y.
 */
struct CurveData {
	OpPoint start;
	OpPoint end;
//	CurveUserData optional;	// user data follows endpoints
};

// offset of user data (if any); immediately follows required curve points
inline size_t CurveUserDataOffset() {
	return sizeof(CurveData);
}

// location of user data
inline std::byte* CurveUserData(CurveData* curve) {
	return (std::byte*) curve + CurveUserDataOffset();
}

// the curve data, its size and type
struct Curve {
    Context* context;
	CurveData* data;
	size_t size;  // total size pointed to by data (in bytes), including additional data, if any
	CurveType type;
};

// convenience for adding curves (e.g., Beziers) to contour
struct AddCurve {
    Context* context;
	OpPoint* points;
	size_t size;	// size of data pointed to by points (in bytes)
	CurveType type;
};

// caller defined data representing how curves in a contour cover area
typedef void* WindingData;

// the winding data and its size
struct Winding {
    Contour* contour;
	WindingData data;
	size_t size;
};

// returns if an edge starts a fill, ends a fill, or does neither and should be discarded
enum class WindKeep {
    Discard,	// must be equal to zero
    End,		// edge ends a filled area
    Start,		// edge begins a filled area
};

// caller defined winding condition type (e.g., contains, overlaps, excludes, ...)
typedef int WindingCondition;

// both first and last may be set
enum class LoopAttribute {
    none = 0,
    first = 1,
    last = 2,
    reversed = 4
};

struct Output {
    Curve curve;
    Winding winding;
    LoopAttribute attribute;
};

// curve callbacks

// intersects the curve and axis at the axis intercept
// !!! move debug roots into context
typedef OpRoots (*AxisT)(Curve , Axis , float axisIntercept  OP_DEBUG_PARAMS(const OpRoots& ));

// returns number of points in curve user data that contribute to its hull
typedef int (*HullPtCount)();

// returns true if all curve values that can describe hull points are finite 
typedef bool (*CurveIsFinite)(Curve );

// returns true if curve is line within the given threshold
typedef bool (*CurveIsLine)(Curve , float threshold); 

// returns OpPoint at parameter t, where: t=0 is start, t=1 is end
typedef OpPoint (*PtAtT)(Curve , float t);

// returns true if additional data is equal (e.g., lines are always equal) 
typedef bool (*CurvesEqual)(Curve , Curve );

// returns point constructs curve's hull; the curve is tightly contained by the hull's polygon
typedef OpPoint (*CurveHull)(Curve, int index);

// map the control points (if any) to lie inside the bounds of the curve (e.g., start and end)
typedef void (*CurvePin)(Curve, OpPoint oldStart, OpPoint oldEnd);

// reverses order of control points, if there is more than one
typedef void (*CurveReverse)(Curve);

// rotates curve user data about origin (not normalized)
typedef void (*Rotate)(Curve , OpPoint origin, OpVector scale, Curve result);

// computes part from parameter t1 to t2, both from 0 to 1
// sets result type to zero if curve part is linear, within threshold tolerance
typedef void (*SubDivide)(Curve , float t1, float t2, OpVector threshold, Curve* result);

// returns tangent vector at parameter t, where: t=0 is start, t=1 is end
typedef OpVector (*CurveTangent)(Curve, float t);

// adds curve user data to bounds
typedef void (*SetBounds)(Curve , OpRect& );

// returns either x or y pair at parameter t, where: t=0 is start, t=1 is end
typedef OpPair (*XYAtT)(Curve , OpPair t, XyChoice );

// overrides engine maximum for a curve type
typedef float (*CurveConst)(Curve );

// the collection of caller defined functions that describe the geometry of the curve
// caller defined functions are optional and default to built-in behavior
struct CurveCallbacks {
	AxisT axisTFuncPtr = nullptr;  // curve is monotonic
	AxisT rotateTFuncPtr = nullptr;  // curve was rotated and may require finding extrema
	CurveHull curveHullFuncPtr = nullptr;
	CurveIsFinite curveIsFiniteFuncPtr = nullptr;
	CurveIsLine curveIsLineFuncPtr = nullptr;
	SetBounds setBoundsFuncPtr = nullptr;
	CurvePin curvePinFuncPtr = nullptr;
	CurveTangent curveTangentFuncPtr = nullptr;
	CurvesEqual curvesEqualFuncPtr = nullptr;
	PtAtT  ptAtTFuncPtr = nullptr;
	PtAtT  ptDAtTFuncPtr = nullptr;
	HullPtCount ptCountFuncPtr = nullptr;
	Rotate rotateFuncPtr = nullptr;
	SubDivide subDivideFuncPtr = nullptr;
	XYAtT xyAtTFuncPtr = nullptr;
	CurveReverse curveReverseFuncPtr = nullptr;
	CurveConst cutFuncPtr = nullptr;
	CurveConst interceptFuncPtr = nullptr;
	CurveConst normalLimitFuncPtr = nullptr;
	CurveConst maxAlternateEndFuncPtr = nullptr;
	CurveConst smallTFuncPtr = nullptr;
	CurveConst maxCutFuncPtr = nullptr;
};

// winding callbacks

// adds winding
typedef void (*WindingAdd)(Winding winding, Winding toAdd);

// subtracts winding
typedef void (*WindingSubtract)(Winding winding, Winding toSubtract);

// returns true if winding affects operation (frame is not wound but is visible)
typedef bool (*WindingVisible)(Winding winding);

// marks winding as having no effect
typedef void (*WindingZero)(Winding toZero);

// returns if curve transitions to a filled area and is kept; or if curve is discarded
typedef WindKeep (*WindingKeep)(Winding winding, Winding sum);

// returns true if winding pair can generate intersections (e.g., frame returns false because
// it does not intersect itself)
typedef bool (*WindingIntersect)(Winding left, Winding right);

// return non-zero to discard subsequent winding operations; condition is returned by resolve 
typedef WindingCondition (*WindingShort)(Context* , WindKeep );

typedef int (*WindingLoopLimit)(Winding );

// the collection of call-defined functions that describe the winding
// !!! to do: can / should remaining winding callbacks have defaults? maybe the unary winding rule?
struct WindingCallbacks {
	WindingAdd windingAddFuncPtr;
	WindingKeep windingKeepFuncPtr;
	WindingSubtract windingSubtractFuncPtr = nullptr;
    WindingVisible windingWoundFuncPtr = nullptr;  // true if contains value that impacts fill
	WindingVisible windingVisibleFuncPtr = nullptr;  // true if curve is visible or affects output
    WindingZero windingZeroFuncPtr = nullptr;
    WindingIntersect windingIntersectFuncPtr = nullptr;
    WindingShort windingShortFuncPtr = nullptr;  // any winding meets kept condition
    WindingShort windingShortAllFuncPtr = nullptr;  // all windings meet kept condition
	WindingLoopLimit windingLoopFuncPtr = nullptr;  // attempts to fix curve/curve intersections
};

// context callbacks

// Common path operations return WindKeep::discard, so that curves are output once.
// adds curve to output
typedef WindKeep (*CurveOutput)(Output);

// initializes caller's path as empty
typedef void (*EmptyCallerPath)(Context* );

// returns the linear type defined by the caller
typedef CurveType (*SetLineType)(Curve );

// overrides a scalar used by the engine to test if curve intersects bounds 
typedef float (*CurveValue)(Curve );

typedef int (*CurveCount)(Curve );

// overrides a scalar used by the engine to intersect a pair of curves 
typedef float (*CurveCurveValue)(Curve , Curve );

// overrides a count used by the engine to intersect a pair of curves 
typedef int (*CurveCurveCount)(Curve , Curve );

// overrides a count used by the engine to limit the memory used to assemble the result
typedef int (*ContextCount)(Context* );

// overrides a scalar used by the engine to describe the error allowed when assembling the result
typedef float (*ContextValue)(Context* );

// the collection of caller defined functions that change the global context behavior
// caller defined functions beginning with 'max' customize when the engine returns an error
// caller defined functions are optional and default to built-in behavior
struct ContextCallbacks {
	CurveOutput curveOutputFuncPtr = nullptr;
	EmptyCallerPath emptyCallerPathFuncPtr = nullptr;
    CurveOutput bestLoopFuncPtr = nullptr;  // can override smallest perimeter for best output loop
	SetLineType setLineTypeFuncPtr = nullptr;  // default to (CurveType) 1
	CurveCurveValue maxAngleMatchFuncPtr = nullptr;
	CurveCurveValue maxAngleSweepFuncPtr = nullptr;
	CurveCurveValue maxSplitFuncPtr = nullptr;
	CurveCurveValue maxBoundedEdgeFuncPtr = nullptr;
	CurveCurveValue maxSignSwapFuncPtr = nullptr;
	CurveCurveValue maxTSlopFuncPtr = nullptr;
	CurveCurveValue maxSplitBiasFuncPtr = nullptr;
	CurveCurveValue maxOverlapFuncPtr = nullptr;
	CurveCurveValue maxUnsectableFuncPtr = nullptr;
    CurveCurveValue maxDistFuncPtr = nullptr;
	CurveCurveCount maxDeepFuncPtr = nullptr;
	CurveCurveCount maxShallowFuncPtr = nullptr;
	CurveCurveCount maxSplitsFuncPtr = nullptr;
	CurveValue maxMarginFuncPtr = nullptr;
	CurveCount rootAdjustFuncPtr = nullptr;
	CurveCount hullNudgeFuncPtr = nullptr;
	CurveValue maxUnsectableTFuncPtr = nullptr;
	CurveValue maxUnsectDistFuncPtr = nullptr;
	CurveCurveCount maxCheckSplitFuncPtr = nullptr;
	ContextCount maxLimbsFuncPtr = nullptr;
	ContextCount maxLoopsFuncPtr = nullptr;
	ContextCount windingBytesFuncPtr = nullptr;
	ContextValue maxGapFuncPtr = nullptr;
	ContextValue linkupScaleFuncPtr = nullptr;
	ContextValue enabledRatioFuncPtr = nullptr;
};

// return true if the engine should abort
typedef bool (*ErrorDispatch)(ContextError , Curve* );

// caller-defined function that determines if an error is fatal
struct ErrorHandler {
	ErrorDispatch errorDispatchFuncPtr;
};

} // namespace PathOpsV0Lib

#endif
